### ISSUE TITLE
implement ad blocker

### ISSUE THREAD

**Issue by Ravan1190** [qolbudr/netflix#1]
its not playing showing too much ads while playing movie.

**Comment by qolbudr** [comment]
looking for implementation on flutter_inappwebview

**Comment by qolbudr** [comment]
check the latest build on actio tab

**Comment by qolbudr** [comment]
> its not playing showing too much ads while playing movie.

check the latest build on action tab

**Comment by Ravan1190** [comment]
> > its not playing showing too much ads while playing movie.
> 
> check the latest build on action tab

i have checked the problem is when i tap on play it show popup ads. everytime

**Comment by qolbudr** [comment]
have been implement ad blocker on this check the latest build

**Comment by DarkCrypt** [comment]
Ad blocker doesn't work, webview is notorious for ads. In-app native player should help and is much better for usability.
