### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by Viddieee** [qolbudr/netflix#3]
Hi! I might be doing something wrong but the app is working. It just keeps on loading but nothing ever gets loading. Could you please help me with the situation?

**Comment by qolbudr** [comment]
please wait working on updates

**Comment by qolbudr** [comment]
closed on 0f4cee8

**Comment by qolbudr** [comment]
closed on 0f4cee8

**Comment by xyschen** [comment]
the issue remains the same
